language: java
jdk:
  - oraclejdk8

install:
  # update mvnw
  - cd ./cie-server
  - mvn -N io.takari:maven:wrapper
  - chmod +x ./mvnw
  - ./mvnw install -Prelease

script:
  cd ./cie-server
  mvn test clean -Prelease