language: java
jdk:
  - oraclejdk8
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE test;'
install:
  - mwn clean install
after_success:
  - mvn clean test jacoco:report coveralls:report
