language: java
jdk:
  - oraclejdk8
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE test;'
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - cd ./cie-server
  - mvn -N io.takari:maven:wrapper
  - mvn clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
  
