sudo: required
language: java
jdk:
  - oraclejdk8
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE test;'
install:
  - cd ./cie-server
  - sudo mvn clean compile
after_success:
  - sudo mvn test jacoco:report coveralls:report
