language: java
jdk:
  - oraclejdk8
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE test;'
install:
  - cd ./cie-server
  - mvn clean compile
after_success:
  - cd ./cie-server
  - mvn clean test jacoco:report coveralls:report
